### ISSUE TITLE
Distinguish between various classes of latency 

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#1]
This might just be "low-latency" versus "not low-latency", but might also reflect the categories used in https://www.ietf.org/archive/id/draft-ietf-mops-streaming-opcons-07.html#section-3 - that's currently finishing up WGLC, so at least some people think those categories make sense.

**Comment by fiestajetsam** [comment]
So we have this, and we've referred back to the opscon draft. I'd actually consider removing the bullet points we have describing them unless we plan on elaborating a bit further the choice of values or the applicability to the work we're doing here.

**Comment by SpencerDawkins** [comment]
@fiestajetsam - yes, agreed. In addition, are we still thinking about <100 ms and/or <500ms? We've talked about <100 ms, and the MOQ BOFREQ is talking about <500 ms. ISTM that we should call those out. What do you think?

**Comment by fiestajetsam** [comment]
I think we covered this in #30 and thus we can close it.
