### ISSUE TITLE
"Media Transport Protocol" terminology

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#12]
I THINK what we are doing, is roughly 

- Start with current "Media - Media Transport Protocol", where "Media Transport Protocol" might be RTP
- Encapsulate in QUIC, to give "Media - Media Transport Protocol - QUIC"

If that's right, we should be using "Media Transport Protocol" to describe the first layer under "Media", and what we're doing might better be described as something like "Media Transport Protocol Encapsulation" ("in QUIC"). 

Whatever we choose, we should be consistent - the Abstract says 

> This document describes the uses cases, requirements, and considerations that should be part of the design of a real-time media protocol over QUIC [RFC9000].

which would make me believe that we're designing a replacement for existing media transport protocols, but then under "Non-requirements, we have 

> The creation of new media transport protocols should be avoided, and instead we should make use of RTP [RFC3550] and the existing ecosystem of payload formats and methods of signalling where possible. 

I think that the second quote is correct, so we just need to be clearer in the first quote.

**Comment by fiestajetsam** [comment]
I think we can close this as our nomenclature for the document is kind of done now the -00 is out.
