### ISSUE TITLE
"Authentication" was unclear for me

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#13]
I needed a bit more context for this: 

> The protocol SHOULD have capabilities asides from TLS mutual authentication to allow hosts to authenticate one another, this should be kept simple but robust in nature to prevent attacks like credential brute-forcing.

I'm probably confused by "The protocol". 

https://www.rfc-editor.org/rfc/rfc9000.html#name-cryptographic-and-transport says it provides this authentication using TLS 1.3 handshake. Are you thinking of 

- something in addition to the QUIC cryptographic handshake? 
- (Assuming the definition of "Media Transport Protocol" in #12), something provided by the Media Transport Protocol level? 
- Or something else?

**Comment by fiestajetsam** [comment]
Closing this as I *think* it has been addressed, please by all means speak up if we still should do work here.
