### ISSUE TITLE
Add section for non-requirements

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#2]
A similar section seemed helpful during discussion of https://www.ietf.org/archive/id/draft-ietf-masque-ip-proxy-reqs-03.html

My first nominee (and I'll put that in the corresponding PR) is that we're assuming that we're working with existing media transport protocols like RTP and SRP, rather than inventing a new media transport protocol in the IETF, but we can talk when I have text.

**Comment by fiestajetsam** [comment]
We have this in place, and I think we have enough non-requirements to start with, let's keep adding as appropriate.
