### ISSUE TITLE
Define "Media over QUIC"

### ISSUE THREAD

**Issue by afrind** [fiestajetsam/draft-gruessing-moq-requirements#27]
Media over QUIC is just the name of a mailing list and a general area of discussion.  In some places, the draft refers to it ambiguously where a read may interpret it as the name of a protocol or working group.  Maybe can call out that it is not those things and disambiguate references with "Media over QUIC mailing list" or "Media over QUIC problem space"?

**Comment by SpencerDawkins** [comment]
I think the issue (or at least the resolution) is also tied to #25 - the objectionable (or at least the obsolete) text in #25 needs to change, and making the changed text also define all the ways we've used the label "MOQ" seems helpful. Expect a PR that attempts to resolve both.
