### ISSUE TITLE
Change document title to "Live Media Over QUIC - Use cases and Requirements"

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#31]
@fiestajetsam and @afrind - It is occurring to me that all the use cases we're recommending in this draft, and all the use cases that are named in [the current MOQ BOF description](https://github.com/afrind/moqbof/blob/main/meeting-materials/bofreq-frindell-media-over-quic.md), are pointing towards LIVE media. 

This document is even explaining why we think that's what matters first. 

If we renamed the document as "Live Media Over QUIC", 
- it would be more accurate, and 
- the BOF proponents could point to this draft and ask people with other use cases if their use cases overlap with the live media use cases, perhaps allowing the BOF to recommend doing the live media use cases in this draft, and inviting people to provide comments on this draft explaining their use cases, so the IESG would know what to do with them. 

Your thoughts?

**Comment by afrind** [comment]
I don't object to the name change but I don't feel strongly.

**Comment by fiestajetsam** [comment]
That name works for me too.

**Comment by SpencerDawkins** [comment]
We should revisit after the BOF

**Comment by SpencerDawkins** [comment]
So, this is slightly more complicated than I had hoped. 

The use cases in the draft span "Media Over QUIC". 

The considerations (and, if we get that far, requirements) in the draft only cover "LIVE Media Over QUIC". 

So, let's leave this one open, until we find out the right thing to do, and then we can Do The Right Thing. :innocent:

**Comment by fiestajetsam** [comment]
I would propose we rename (again) to "Media over QUIC Use Cases and Requirements", for a few reasons:

* Scope of use cases that the WG will work on isn't yet settled, and it's likely that we may need to cover _some_ (but not all) interactive use cases as well as hybrid interactive/live.
* I still think we should set the protocol requirements in the document - this frees up the charter to describe scope and milestone, and our draft (if WG adopted) to set the use cases and what we will require of the deliverables. If WG adopted, the details of what is in and out can be made via WG consensus.
* This follows a similar title format to [RFC 7478](https://datatracker.ietf.org/doc/html/rfc7478) and other documents like it.
@SpencerDawkins  thoughts?
