### ISSUE TITLE
DVR use case

### ISSUE THREAD

**Issue by kixelated** [fiestajetsam/draft-gruessing-moq-requirements#33]
HLS and DASH support seamlessly switching between live and recorded content. It's arguably the most annoying use-case to support but maybe it should be mentioned. I absolutely would not include it in the initial scope.

**Comment by fiestajetsam** [comment]
In 61750a157 I included what should be enough to cover this as part of the existing Live Media Streaming use case. Given the current position is not to work on On Demand, psuedo-VOD should also be out of scope too I think. Thoughts?

**Comment by kixelated** [comment]
I would put it under a separate use-case or omit it entirely. It's not used by most "live media streaming" products in my experience.

**Comment by fiestajetsam** [comment]
My experience differs significantly.

Rewind windows with multi-hour (even days) in duration are, at least for most of the video I handle a key requirement in both on demand generation (either Live to OD, Pseudo OD, or RoT compliance/confidence copying), and when offered to end users is a significantly popular feature not just for simulcast output, but also for time sensitive events like sporting matches.

I don't think that live rewind belong in a separate use case as it's an optional extension of live media playback capabilities, whereas on demand generation has sections already. If you still feel quite strongly about this I'd be happy to look at any changes you'd propose.
