### ISSUE TITLE
Non-Requirement: New Media Transport Protocols

### ISSUE THREAD

**Issue by kixelated** [fiestajetsam/draft-gruessing-moq-requirements#35]
I've already ranted enough about this section but I figured I'd file a ticket so it doesn't get forgotten. :)

**Comment by fiestajetsam** [comment]
I think what needs changing is that this is removed as a non-requirement, _however_ I still think that we have to make it clear that a consideration "to RTP or not to RTP" must be described in the document.

**Comment by fiestajetsam** [comment]
I think we've now covered this, please chime up if there was anything missed.
