### ISSUE TITLE
Distinguish between stream and datagram use cases

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#4]
This will be easier to get right initially, than to realize that we need to distinguish these use cases later on.

**Comment by fiestajetsam** [comment]
I don't think we should do this as part of the requirements as it's too nitty-gritty a detail. Instead requirements around reliability, flow control, among others will ultimately determine which frame types are used. Please let me know if you still think this deserves our attention at this stage.
