### ISSUE TITLE
Explain "why not RTMP or SRT" in Section 6.1

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#46]
From @gloinul: 
> 6.1: 
> 
> The second group of classifications, covering Live Media Contribution (Section 5.5), Syndication (Section 5.6), and Streaming (Section 5.4) are likely the use cases likely to benefit most from this work. Existing protocols used such as HLS [RFC8216]and DASH [DASH]are reaching limits towards how low they can reduce latency in live streaming and for scenarios where low-bitrate audio streams are used add a significant amount of overheads compared to the media bitstream.
> 
> Isn't this totally glossing over the RTMP and SRT contribution and their different shortcomings than HLS and DASH?

**Comment by SpencerDawkins** [comment]
@gloinul and @fiestajetsam - I agree with Magnus in his email (cut and pasted in the description), where he said "what about RMTP and SRT?", but I'm thinking that since we already have a "Why  QUIC?" section, we should probably have a "Why NOT other protocols" section, rather than trying to talk about that in (what was) Section 6.1. 

That could also conveniently map into saying why we're not looking at "Interactive Media" in this document (and, transitively, in the BOF), and why we're not looking at "On Demand" (Media) in this document (and in the BOF). 

Please let me know if this is a BAD idea soon (I'm typing PRs).

**Comment by fiestajetsam** [comment]
@SpencerDawkins for media ingest, Magnus has a good point about covering not just HLS and DASH, but also making (even brief) reference to non-segmented protocols like RTMP and SRT (but really, this can be expanded to RIST, ZiXi, etc etc etc). This can just be a sentence or two; I'm happy to write it.

**Comment by SpencerDawkins** [comment]
@fiestajetsam - I had a complicated day yesterday, which became less complicated last night, so I'm not coherent enough to type text. I'll see what I can do in the next couple of hours, and if I can include these @gloinul suggestions.
