### ISSUE TITLE
Do we need an RTP-equivalent mapping to QUIC, similar to https://datatracker.ietf.org/doc/draft-ietf-quic-http/?

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#6]
ONE of the questions in this direction is "do some media transport applications require continuous operation during QUIC connection migration?"

**Comment by fiestajetsam** [comment]
Based on the other discussions we've been having, I think this is not the path we should take for now. Happy to come back to this if you think I'm wrong.
