### ISSUE TITLE
Repairs to Prior Art/Acks?

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#66]
The ACKs section still says 

> The authors would like to thank the many authors of the specifications referenced in [Section 3](https://github.com/fiestajetsam/draft-gruessing-moq-requirements/issues/new#priorart) for their work:

But only one specification is mentioned in Section 3 (the others were removed). 

> 3. Prior and Existing Specifications
> Several draft specifications have been proposed which either encapsulate existing Media Transport Protocols in QUIC, or define their own new Media Transport Protocol on top of QUIC. Some have already seen deployment into the wild (e.g. [I-D.draft-kpugin-rush]) where as others are unconfirmed.

Would it make sense to just list the prior art drafts in Section 3, so people know what we looked at?

**Comment by fiestajetsam** [comment]
I think this has been cleared up with the above-mentioned commit, now in -02.
