### ISSUE TITLE
Supported media packaging 

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#78]
Starting thesis: The specification should

- support CMAF, 
- in addition to CMAF, support non-contained {"RAW Elementary bitstream") media, and 
- have agility to accommodate future container formats

**Comment by fluffy** [comment]
A bunch of good comments get made in room but from requirement point of view, I think we need to have the ability to use something that  has less overhead than CMAF particularly for audio.  I don't see the need to use multiple types of containers in the same session and have them synchronized.

**Comment by SpencerDawkins** [comment]
This issue was discussed at the MOQ interim meeting on 2023-01-31 - notes from that meeting are [here](https://notes.ietf.org/notes-ietf-interim-2023-moq-03-moq?edit), and included here by reference. 

Anyone working on a PR for this issue should take a look at the discussion notes.

**Comment by SpencerDawkins** [comment]
Hi, @suhashere, would you be able to do a PR for this issue? This isn't my area of clue.

**Comment by SpencerDawkins** [comment]
On today's authors' call, we think **the starting point** is now

- have agility to accommodate a variety of container formats
- support CMAF,
- support media formats that are not processed by relays (and relay-related MOQ capabilities)

This document should also describe the requirements for additional container formats.

**Comment by SpencerDawkins** [comment]
> On today's authors' call, we think the starting point is now
> 
> - have agility to accommodate a variety of container formats
> - support CMAF,
> - support media formats that are not processed by relays (and relay-related MOQ capabilities)

@fiestajetsam - do you think what's in the document now (which isn't quite this ^^^^) is sufficient for an adoption call, or should we do a quick PR just retitling and rearranging the subsections?

**Comment by SpencerDawkins** [comment]
We want agility, and we'll say that as a requirement, but we don't care what a MTI packaging would be (CMAF, fMP4, don't care), and we can defer to the protocol specification(s) (ex. WARP) to state those details, because those specifications will need to handle that anyway. 

It is likely that we need to handle codecs the same way (agility is the requirement, but we don't care about that, and the protocol specifications will need to handle that anyway).

**Comment by SpencerDawkins** [comment]
What the document says now: 

> Packaging of media describes how encapsulation of media to carry the raw media will work. There are at a high level two approaches to this:

> - Within the protocol itself, where the protocol defines the carrying for each media encoding the ancillary data required for decoding the media.
> - A common encapsulation format such as ISOBMFF which defines a generic method for all media and handles ancillary decode information.
> The working group must agree on which approach should be taken to the packaging of media, taking into consideration the various technical trade offs that each provide. If the working group decides on a common encapsulation format, the mechanisms within the protocol SHOULD allow for new encapsulation formats to be used.
