### ISSUE TITLE
Characterize large-scale live streaming use cases

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#91]
In [on-list discussions with @aboba during the call for MOQ adoption](https://mailarchive.ietf.org/arch/msg/moq/CfdP-_fIhgV2nME-w0GaKc8_2Tw/) of this draft, we seem to have converged on characterizing large-scale live streaming use cases as a way to make progress that would help us

- clearly describe a specific, high-value "Media Over QUIC" use case in enough detail for us to identify the resulting requirements, and 
- help us agree on useful attributes that we should include for other use cases we consider to be in scrope for MOQ. 

We have had conversations about specific sporting events, such as the World Cup, and we have had conversations about whether other specific large-scape live streaming use cases would differ from sporting events in any meaningful way. The best way to figure that out is to start doing the work, and see what we find out.

**Comment by SpencerDawkins** [comment]
In discussions with @fiestajetsam, I'm now convinced that using prose is WAY more likely to be useful than the comparison template I was envisioning.

**Comment by fiestajetsam** [comment]
Thought: Put something in about the "scale" of interactivity being a bandwidth limitation - the more entities you have, the less overall metaphorical interactive bandwidth* you have available. This may help better define the boundaries between for example, "Live" and "telephony" use cases where scenarios like "staff all hands" blurred things a bit.

<sup>\* I'm not talking about network bandwidth here, this is human bandwidth to consume what is being received</sup>
