### ISSUE TITLE
Explain the plan for this draft, given that MOQ has a milestone for adoption, but not for publication

### ISSUE THREAD

**Issue by SpencerDawkins** [fiestajetsam/draft-gruessing-moq-requirements#92]
During the [chairs' adoption poll for this draft](https://mailarchive.ietf.org/arch/msg/moq/qOjHbWpGyhRsIiaUgZHgB3EWGRk/), @LPardue asked

> As a point of administration, I don't see a corresponding milestone for submission of a document to the IESG. Can I ask the chairs to clarify if the intention is to adopt and develop a draft but not seek taking it through to an RFC*?

I answered (even though I'm not a MOQ chair), [here](https://mailarchive.ietf.org/arch/msg/moq/sI0v-40anUn8WzFOwKpTc1vnq34/), but it's worth noting that this question has come up more than once during MOQ meetings, so it seems useful to add a short summary to the draft, in order to make sure we all have the same understanding. 

If I get this wrong, @hardie and @afrind can correct me, of course. :innocent:

**Comment by LPardue** [comment]
Ta
